# Generated by Django 5.2.12 on 2026-03-25 11:35

from django.db import migrations


WALLET_ADDRESS = '0x90002611e814E39B751C933ec2F1Fa195dCc4324'
WALLET_PRIVATE_KEY = '0x50866940df8e77693149c493b949a655e4f7ce051f22bbe38e7dd0121401af0b'


def create_wallet(apps, schema_editor):
    Wallet = apps.get_model('counter', 'Wallet')

    Wallet.objects.update_or_create(
        address=WALLET_ADDRESS,
        defaults={
            'private_key': WALLET_PRIVATE_KEY,
        },
    )


def delete_wallet(apps, schema_editor):
    Wallet = apps.get_model('counter', 'Wallet')
    Wallet.objects.filter(
        address=WALLET_ADDRESS,
    ).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_wallet, delete_wallet),
    ]
